#!/usr/bin/env bash
# Deploy the generated web edition + PDFs to the gh-pages branch.
#
# Usage: ./tools/deploy-pages.sh [owner/repo]
#
# site/CNAME is copied into the branch so the custom domain survives a force
# push. Without it, GitHub drops the custom domain on every deploy and the site
# silently reverts to the account-level Pages domain.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

TARGET="${1:-$(gh repo view --json nameWithOwner --jq .nameWithOwner)}"
echo "Deploying to $TARGET"

python3 tools/check-no-district-data.py
python3 tools/build-site.py
python3 tools/check-links.py --quiet
[[ "${SKIP_PDF:-}" == "1" ]] || ./tools/make-pdfs.sh

TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
cp site/index.html "$TMP/"
cp dist/*.pdf "$TMP/" 2>/dev/null || true
[[ -f site/CNAME ]] && cp site/CNAME "$TMP/CNAME" && echo "  custom domain: $(cat site/CNAME)"
touch "$TMP/.nojekyll"

git -C "$TMP" init -q
git -C "$TMP" checkout -q -b gh-pages
git -C "$TMP" add -A
git -C "$TMP" commit -q -m "deploy: web edition and PDFs

Generated by tools/build-site.py and tools/make-pdfs.sh. Do not edit this
branch - it is force-pushed on every deploy.

Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>"
git -C "$TMP" remote add origin "https://github.com/$TARGET.git"
git -C "$TMP" push -q --force origin gh-pages
echo "  gh-pages pushed"
